version: "3.3"

services:
  postgres:
    image: postgres:12-alpine
    container_name: postgres
    restart: always
    environment: 
      POSTGRES_USER: root
      POSTGRES_PASSWORD: t6QRbZJaM5aGed3W
    ports:
      - 5432:5432
    volumes:
      - /home/data/app/postgresql/data:/var/lib/postgresql/data
